group:
  default:
    localsave: true
    recall: true
    warn: false
    notice: true
    mute: false
    mute_time: 60
    mutecount: 1
  "755269874":
    localsave: true
    recall: false
    warn: false
    notice: true
    mute: false
    mute_time: 60
    mutecount: 1
private:
  localsave: true
  warn: false
  notice: true